# Generated by Django 4.2.2 on 2023-07-25 01:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('distric', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'areas',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id_booking', models.AutoField(primary_key=True, serialize=False)),
                ('date_booking', models.CharField(max_length=200)),
                ('service_booking', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(max_length=200)),
                ('vehicle_number', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=200)),
                ('extra', models.CharField(max_length=200)),
                ('detail', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('id_company', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='Carbrand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'carbrand',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('company_certificate', models.CharField(max_length=200)),
                ('company_photo', models.CharField(max_length=200)),
                ('company_description', models.TextField(max_length=200)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Admins.area')),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_customer', models.AutoField(primary_key=True, serialize=False)),
                ('customer_first_name', models.CharField(max_length=100)),
                ('customer_second_name', models.CharField(max_length=100)),
                ('customer_last_name', models.CharField(max_length=100)),
                ('customer_email', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=100)),
                ('customer_address', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('customer_password', models.CharField(max_length=200)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('company_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='Admins.company')),
                ('id_booking', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Admins.booking')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.CharField(max_length=100)),
                ('lng', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'map',
            },
        ),
        migrations.CreateModel(
            name='owners',
            fields=[
                ('id_owner', models.AutoField(primary_key=True, serialize=False)),
                ('owner_first_name', models.CharField(max_length=200)),
                ('owner_second_name', models.CharField(max_length=200)),
                ('owner_last_name', models.CharField(max_length=200)),
                ('owner_email', models.CharField(max_length=200)),
                ('owner_phone', models.CharField(max_length=200)),
                ('owner_address', models.CharField(max_length=200)),
                ('owner_password', models.CharField(default='1234', max_length=200)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('role', models.CharField(default='1', max_length=200)),
                ('status', models.CharField(default='1', max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admins.company')),
            ],
            options={
                'db_table': 'owner',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id_payment', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('date_payment', models.DateField(auto_now=True)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id_schedule', models.AutoField(primary_key=True, serialize=False)),
                ('worker_id', models.IntegerField(default=0)),
                ('workorder_id', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
        migrations.CreateModel(
            name='Typeofvehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('types', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'typeofvehicle',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('worker_first_name', models.CharField(max_length=100)),
                ('worker_second_name', models.CharField(max_length=100)),
                ('worker_last_name', models.CharField(max_length=100)),
                ('worker_address', models.CharField(max_length=100)),
                ('worker_email', models.CharField(max_length=100)),
                ('worker_date_of_bath', models.CharField(max_length=200)),
                ('worker_phone', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('id_schedule', models.IntegerField(default=0)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Admins.owners')),
            ],
            options={
                'db_table': 'worker',
            },
        ),
        migrations.CreateModel(
            name='Workorder',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('date_order', models.DateTimeField(auto_now_add=True)),
                ('type_order', models.CharField(default='offline', max_length=200)),
                ('status', models.IntegerField(default=1)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Admins.area')),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Admins.booking')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Admins.customer')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Admins.worker')),
            ],
            options={
                'db_table': 'workorder',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id_vehicle', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_owner_number', models.CharField(max_length=100)),
                ('vehicle_brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Admins.carbrand')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Admins.typeofvehicle')),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='id_vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admins.vehicle'),
        ),
        migrations.AddField(
            model_name='company',
            name='map_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Admins.map'),
        ),
    ]
